### ISSUE TITLE
Getting started page is redundant

### ISSUE THREAD

**Issue by shohamc1** [turtlecoin/turtlecoin-wiki#130]
[This page](https://github.com/turtlecoin/turtlecoin/wiki/Getting-Started#new-wallet) is redundant. You should directly link to the respective guides from the main page itself.

**Comment by Sajo811** [comment]
Can you give more details and an explanation as to why it is so? "this page is redundant" doesn't mean anything.

**Comment by shohamessi** [comment]
It doesnt serve any inherent purpose, removing the page would make it simpler. Also because both Mining and Wallets leads to the same page.

**Comment by SoreGums** [comment]
hmm - It is not clear how removing it makes things clear or having it means it is in the way.

It clearly creates a path of "u need a wallet, get one", now "go mine" and finally "come chat with us".

where else on the site does it lay out this direct path?

it is really not clear how deleting this page makes everything +1

**Comment by shohamc1** [comment]
What the the main page for then. That clearly says “a guide on setting up a wallet”, but doesn’t send you to the guide. It’s more understandable for the mining page, but IMO it just complicates it. It’d be better if you remove the page and send the user to 
https://github.com/turtlecoin/turtlecoin/wiki/Making-a-Wallet for wallets and

https://github.com/turtlecoin/turtlecoin/wiki/Mining for mining. Make a new section in the mining page saying that you need a wallet to mine and link it to the wallets page

**Comment by Sajo811** [comment]
Adding a section on making a wallet in mining is just fluff,  why not leave the getting started page as it is, nice and clean? 

The home page exists to welcome people and help them quickly navigate to places of potential interest, they cna use the sidebar if they want to go to a guide in mind.

If you feel the link in the navigation table is redundant when it links to the getting started guide, then the question arises whether to change those links, not remove the whole page altogether

**Comment by Sajo811** [comment]
Read my post again, and your post again ;) @shohamc1

**Comment by shohamc1** [comment]
Never mind, it seems like it is fine. Close the issue
