### ISSUE TITLE
[Idea] Developer resources page 

### ISSUE THREAD

**Issue by ar-x** [turtlecoin/turtlecoin-wiki#131]
As an interim solution, I would like to create **a** page on the wiki which lists (just links to other pages) development resources. 

Criteria: Resources which help developers and designers develop TurtleCoin, and for TurtleCoin.

Unfortunately, I don't have a good idea of what the content here should be. I was thinking these sections:

### Docker Images
* Links to relevant docker images.

### Reads
* Link to relevant ByteCoin docs 
* https://hackmd.io/s/H1IWL1fRM

### API

* Links to TurtleCoin API client libraries
* Link to TurtleCoin API Docs (https://hinata-104.shadow-clone-jutsu.com/, hopefully at `api-docs.turtlecoin.lol` soon)
* Link to relevant ByteCoin docs 

----

My plan is to add a nav item (on top, at turtlecoin.lol) called **Guides** with these dropdown items :

1. User Guides - the wiki
2. Developer Resources -  this one page.
3. Brand Guidelines - link to the Brand page (https://turtlecoin.lol/brand.html) which I'm currently fixing/revamping.

(1) and (2) would just open GH pages in a new tab.

---

### This

Let me know what you all think, and I can take it up. If you think its a good idea, please point out good candidates for the developer resources page keeping the criteria above in mind. The actual content, organization of the page can be decided over a PR.

**Comment by ar-x** [comment]
The longer term plan is to have a our own site for developer resources - but thats a little far out since I'm not sure if there is content already written for it.

**Comment by fexra** [comment]
Bebop and I been talking about this forever. A simple developer.turtlecoin.lol single page site would be perfect. All it would have to do is link to all the libraries, docker images, packages, and dev wiki. 

I think it should mainly just link all the libraries we created and are hosted on turtlecoin gitHub. Eg: npm, laravel, woocommerce, etc packages.

**Comment by ar-x** [comment]
>  A simple developer.turtlecoin.lol single page site 

Ok I was just thinking about linking directly to a page on the `turtlecoin/turtlecoin-wiki`. Its just simpler that way I think, saving time to build a `developer.turtlecoin.lol` - which I assume would have more content? I'm fine either ways.

>  and dev wiki.

what is that?

**Comment by SoreGums** [comment]
fexra that sounds a lot like https://github.com/turtlecoin/meta/issues/86

which i was proposing going to the docs, be obvious from the 1st page and in any navigation menus

**Comment by ar-x** [comment]
I'm trying to solve my other itch here - How do I get started as a interested developer.  I found it hard to get started on TurtleCoin since the *technical* resources are scattered all over. Some of them were *community*, some *non community*, some *external*. So I had to rely on Discord a little too much. This tackles that. 

To see _all_ projects, I would just look at _all_ repos under the turtlecoin org. And yes, since the projects are tagged community, it tells me about that.

I'm not trying to implement a bigger vision here, just something which I think is useful for me - to get started.

**Comment by ar-x** [comment]
PR: https://github.com/turtlecoin/turtlecoin-wiki/issues/131

**Comment by ar-x** [comment]
The wiki content was merged in. Similarly my plan is to create content for the Community Projects page, and then consume both on turtlecoin.lol which is being turned into a Jekyll site. This *might* make the http://turtleturtle.org site redundant.  Is it important to keep that site? (so that it stands out as community not official?).

**Comment by ar-x** [comment]
Also since turtlecoin.lol is being localized - both `md` files would need localization.

**Comment by SoreGums** [comment]
I see turtleturtle.org as a directory of website links - whereas all this documentation stuff is core documentation stuff including all the info about the projects hosted under TurtleCoin GH org.

Like community projects includes the actual documentation repo currently (turtlecoin/turtlecoin-wiki) and how to edit that is going to be a guide which lives in that realm. just like there is a Go wallet library for walletd API, its guides and docs would go under the community heading.

**Comment by SoreGums** [comment]
EDIT: just realised I'm talking about community "projects" - maybe you are referring to all the things running for real as part of the community turtlecoin/meta#86 not the source projects and associated documents?

**Comment by fexra** [comment]
I'm not referring to any documentation or detailed information. I think we are all thinking of a few different things here in this thread. Most discussed here should in the wiki, like you two said @SoreGums and @ar-x . 

What I was referring to is a one page developer portal with a simple overview of what SDK's, wrappers, tools, etc are out there. It will contain a link to our developer wiki and other important resources. Than under that we would have links to a few selected community projects from the  GitHub that are useful for developers such as SDKs, wrappers, docker images, etc (eg: turtlecoin-walletd-rpc-js, turtlecoin-walletd-rpc-python, turtlecoin-walletd-rpc-go, turtlecoin-walletd-rpc-php, turtlecoind-rpc-js, turtlecoind-ha, etc) This could also be a place where we can link other resources such as design assets and brand guidelines.

At the moment there is no good overview of what API's, SDK's, etc we have and in which languages. Here are some examples of developer pages:

https://developers.smartsheet.com/
https://developer.amazon.com
https://developer.pebble.com/
https://developer.r-project.org
https://developer.android.com/
 https://developers.arcgis.com
https://developer.box.com
https://beta.developer.spotify.com

**Comment by SoreGums** [comment]
I get you Fexra - looks like my comments were about ar-x posts above mine.

so ar-x - when say put it all on turtlecoin.lol - just not clear what you meant.

We'll get there eventually everyone :D

**Comment by ar-x** [comment]
> At the moment there is no good overview of what API's, SDK's, etc we have and in which languages. Here are some examples of developer pages:

Yep, I think the long term plan is to have a developer portal like your examples. Here I was just calling for a low effort interim solution, [like what we have now](https://github.com/turtlecoin/turtlecoin-wiki/wiki/Resources), which can directly be linked from the website. I will indeed be looking into this in a bit.

> so ar-x - when say put it all on turtlecoin.lol - just not clear what you meant.

I'm still mulling over this, lets discuss this once I'm done ;)

My main intention here is to link to wiki pages from turtlecoin.lol - while we build out proper sites for it. So I'm thinking about doing while we build out the frontends). See this section on my first comment above.

> My plan is to add a nav item (on top, at turtlecoin.lol) called **Guides** with these dropdown items
