### ISSUE TITLE
Copy Revision Inquiry

### ISSUE THREAD

**Issue by unijohn** [turtlecoin/turtlecoin-wiki#5]
> Go to http://chat.turtlecoin.lol and post your wallet address in #wallets and we will get you started with some TRTL to kick the tires a little bit :). You can also use the automated faucet for 10 TRTL's up to 10 times a day - http://faucet.trtl.me/

The error message now states it will only work up to 3 times per day...?

**Comment by unijohn** [comment]
See #6

**Comment by BebopTC** [comment]
Ah yup, the faucet changed. Will update. Working on revising the docs system a bit and hopefully that will help things stay more up-to-date moving forward.

**Comment by BebopTC** [comment]
Been fixed.
