### ISSUE TITLE
Should the FAQ have a donation address?

### ISSUE THREAD

**Issue by Sajo811** [turtlecoin/turtlecoin-wiki#69]
Given this is a wiki maintained by a community-effort and has many people contributing towards one/multiple guides/resources, does it make sense for 1 person to claim responsibility of making a whole guide/resource and hint people at tipping him, even if he did make the raw guide. It must have inevitably witnessed commits from other people.

I'm talking about this article- https://github.com/turtlecoin/turtlecoin-wiki/blob/master/faq/Frequently-Asked-Questions.md

Would like your opinions on whether or not donation addresses in this wiki should be permitted

Thanks

-S8

**Comment by ZedPea** [comment]
Yeah, it should be removed.

source: it's my donation address

**Comment by ZedPea** [comment]
I don't have too strong feelings on it. It comes across as a more professional feel if all the documentation is in the same style and appears to come from one source rather than several, I suppose.
