### ISSUE TITLE
Copy / Disclaimer Revision

### ISSUE THREAD

**Issue by unijohn** [turtlecoin/turtlecoin-wiki#7]
re:  Getting-Started-w--TurtleCoin-on-Windows.md

> 7. You're done! Copy your spend key and view key and email them to yourself so that you can restore your wallet if it breaks or if you lose it!!!

With the rapid growth and interest in TRTL, does the group want to suggest such an insecure manner for key storage/transport?

**Comment by BebopTC** [comment]
Good point! Will revise

**Comment by BebopTC** [comment]
Fixed in 1508d9f. Thanks!
